pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_REGION = 'ap-south-1'  // Set your desired AWS region here
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Create EC2 Instance') {
            steps {
                sh 'python create_instance.py'
            }
        }
    }
}
