pipeline {
    agent any
    stages {
        stage('Create IAM User') {
            steps {
                withAWS(credentials: 'admin', region: 'ap-south-1') 
                {
                    sh 'python create_user/create_user.py'
                }
            }
        }
    }
}
