pipeline {
    agent any
    stages {
        stage('Create Policy') {
            steps {
                withAWS(credentials: 'admin', region: 'ap-south-1') 
                {
                    sh 'python pipeline4/policy.py'
                }
            }
        }
    }
}
