pipeline {
    agent any
    stages {
        stage("Clone Git Repository") {
            steps {
                git(
                    url: "https://github.com/rohanmane21/Python/tree/Testing/pipeline2.git",
                    branch: "Testing",
                    changelog: true,
                    poll: true
                )
            }
        }
    }
}
