pipeline {
    agent any
    stages {
        stage('Create Policy') {
            steps {
                withAWS(credentials: 'admin', region: 'ap-south-1')  
                    {
                        echo 'Hello'
                    }
            }
        }
        stage('Policy') {
            steps {
                build job: 'create_policy', wait: false
            }
        }
        stage('User') {
            steps {
                build job: 'create_user', wait: false
            }
        }
        stage('Map') {
            steps {
                build job: 'map_policy', wait: true
            }
        }
    }
}
