pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
        AWS_ACCESS_KEY_ID     = credentials('admin')
        IAM_USERNAME = 'new55'
        GIT_REPO_URL = 'https://github.com/rohanmane21/Python.git'
    }
  stages{
    stage('Check Credendtial'){
        steps {
                script {
                    git branch: 'Testing', credentialsId: 'git-token', url: env.GIT_REPO_URL
                }
            }
    stage('Create IAM User') {
            steps {
                script {
                    sh """
                        aws iam create-user --user-name ${env.IAM_USERNAME}
                    """
                }
            }
        }
    }
  post{
    success{
      sh 'python Gmail/success.py'
    }
    failed{
      sh 'python Gmail/failed.py'
    }
  }
  }
