pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
        AWS_ACCESS_KEY_ID     = credentials('admin')
        IAM_USERNAME = 'new55'
        GIT_REPO_URL = 'https://github.com/rohanmane21/Python.git'
    }
  stages{
      stage('Adding git credentials'){
            steps {
                script {
                    git branch: 'Testing', credentialsId: 'Git-Token', url: env.GIT_REPO_URL
                }
            }
        }
      stage('Create IAM User') {
            steps {
                script {
                    sh """
                        aws iam create-user --user-name ${env.IAM_USERNAME}
                    """
                }
            }
        }
    }
  post{
    success{
      sh'python Gmail/success.py '
    }
    failure{
      sh'python Gmail/failed.py '
    }
  }
  }
  
